### ISSUE TITLE
I2P+ displaying a different router console after recent update

### ISSUE THREAD

**Issue by WatchOfTime** [I2PPlus/i2pplus#1280]
Instead of displaying the I2P+ console, it displayed the official I2P one and the settings had different configurations. I don't know if this is my fault though. But I think it's worth looking into.
Edit: It seems to happen when I restart or shut down the tunnels.

**Comment by vituperative** [comment]
That sounds like you may have inadvertently updated to the stock I2P. If you browse to http://127.0.0.1:7657/configupdate and enable unsigned updates, save, and then check for updates, you should be presented with an I2P+ update. Note that you may need to hard refresh the browser (CTRL+SHIFT+R) post-install.
